### ISSUE TITLE
Welcome Screens

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#10]
1. Please show only the fields which are in old admin
2. Need validation
![image](https://user-images.githubusercontent.com/5259557/181827385-47ad9f16-972c-46bf-87db-bcb3f6364f5c.png)

**Comment by sunnan1** [comment]
![Uploading image.png…]()

Added

**Comment by sharjeelz** [comment]
@sunnan1 

wrong message and validation
![image](https://user-images.githubusercontent.com/5259557/182244663-822bc44f-a8bc-48f1-8467-38358d0265ae.png)

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182300805-74131716-f971-42bc-9f21-91dfdd5f97d9.png)
I updated the same and no error message show tried 10 times but no issue found

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182300897-19d0554d-4e45-4d6b-8061-a3315e9df53e.png)

Even though updated the picture
