### ISSUE TITLE
Canellation Reasons

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#17]
1. Needs validation 
![image](https://user-images.githubusercontent.com/5259557/181828939-8da9437a-543e-4334-9e3a-3e40aa8549a1.png)

**Comment by sunnan1** [comment]
Done

**Comment by sharjeelz** [comment]
@sunnan1 validation is ok , we are missing seeder for this, plz add

**Comment by sunnan1** [comment]
Seeder Added
