### ISSUE TITLE
Memberships

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#18]
1. Needs validation (numeric values also)
![image](https://user-images.githubusercontent.com/5259557/181829066-c949aaf7-d516-47e0-b088-da254791fabb.png)

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182013969-15e65c88-11aa-482c-bae0-4908f6e18f51.png)

Added

**Comment by sharjeelz** [comment]
@sunnan1  bro comission percentage must be number, rest is good

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182301529-27c1a611-32a5-47ba-88a7-ec12686d799b.png)

Fixed
