### ISSUE TITLE
Ad. Banners

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#19]
1. Needs validation

![image](https://user-images.githubusercontent.com/5259557/181829254-0245d85f-c91f-4eb6-b8c2-e97272de5f93.png)

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182014020-08b3e693-b67b-437a-a8e2-3ff764f55ff5.png)

Added

**Comment by sharjeelz** [comment]
@sunnan1  what is the issue with image? why avatar does not show and also no image upload works, do we need to set somehthing in filesystem or what?

**Comment by sunnan1** [comment]
you need to have default.png in public folder then set APP_URL to APP_URL=http://127.0.0.1:8000 , also There might be record in database but no actual file so it will show you a broken image.

![image](https://user-images.githubusercontent.com/16976650/182302331-237f0c2b-edb5-4152-b3b1-2eb863546a54.png)
