### ISSUE TITLE
Store Managers

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#20]
1. Need data from locations for country and city ( DB will be given soon with location data for seeding)
2. Store Type is missing from fields
3. Rename fields as in old admin

**Comment by sunnan1** [comment]
Need data from locations for country and city ( DB will be given soon with location data for seeding) ( Function added in Seeder )
    Store Type is missing from fields ( Rename issues, Fixed )
    Rename fields as in old admin ( Done )
Validation also added
