### ISSUE TITLE
Payment Methods

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#22]
1. Needs Validation
![image](https://user-images.githubusercontent.com/5259557/181830076-28c8078e-9660-46bf-9ce1-ffa98bac3372.png)

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182016263-3bc7eec8-4e40-4b83-a2ac-cd2ec2b5ce20.png)

Added

**Comment by sharjeelz** [comment]
Brother do not close issues until i re verify them

![image](https://user-images.githubusercontent.com/5259557/182143054-6b6a07e1-b363-45a2-8240-f869567cd9c2.png)

**Comment by sharjeelz** [comment]
@sunnan1  bro need validation on drop boxes as well

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182302729-8d1ff6c5-bb06-49db-af12-5f02529eee51.png)

Done
