### ISSUE TITLE
Orders/Advertisments

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#23]
1. On listing show only data which is in old admin
2. Relation with reports missing
3. if an order is in active state(as old admin active listing state) when clicked on edit and change status a reason is asked(needs to be added here) only on cancel status, other wise on status change we need to test what logic is in old admin and how it is updated)
![image](https://user-images.githubusercontent.com/5259557/181831055-59daf66f-9c96-4f44-9ecb-066eca821d6a.png)
4. Notification or any other logic when the status is changed needs to be checked from old admin

**Comment by sunnan1** [comment]
Listing fixed
Relation Added
Observer is not working for statuses

**Comment by sharjeelz** [comment]
1. reports relation missing
2. requirement relation missing

@sunnan1

**Comment by sharjeelz** [comment]
@sunnan1 

in edit not all fileds are showing

![image](https://user-images.githubusercontent.com/5259557/182245146-8076e7cf-129b-432e-b712-ef3c1f4e2dc7.png)

**Comment by sharjeelz** [comment]
@sunnan1  instead of using observer use action functionality of nova to update the status

**Comment by sunnan1** [comment]
@sharjeelz not all fields are editable only charges, date and status is editable and so that is in nova, for status am adding Actions

![image](https://user-images.githubusercontent.com/16976650/182598808-c80ad114-633a-4e50-af8b-251cca9ab63e.png)

**Comment by sunnan1** [comment]
Status added as Action

**Comment by sunnan1** [comment]
FCM added but i can't receive notification on device also this can be tested on their own firebase credentials

**Comment by sharjeelz** [comment]
![image](https://user-images.githubusercontent.com/5259557/182943034-701ed102-1643-421b-842a-4f4d708d79d9.png)
