### ISSUE TITLE
Service Providers

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#24]
1. Need relations
2. In join requests filter and join requests  filter ( see old admin an option comes in to accept or reject ) more over on delete there may be a logic for notification) needs fixing
3. The status drop down coming from backend also has logic some users with certain permissions and type are allowed to have some or all options please see the retrieval of the status drop down.
![image](https://user-images.githubusercontent.com/5259557/181832251-13ee1d94-09aa-46ad-b4db-e0055a6d551c.png)

![181147746-1bf18bf7-46bd-4055-a0fb-19271fe03a50](https://user-images.githubusercontent.com/5259557/181832437-a712b1f0-5e19-4e61-8117-2bb18dc1f9ce.png)

**Comment by sharjeelz** [comment]
@sunnan1  also for images we need to find a way to show them plz research on this

**Comment by sunnan1** [comment]
Join Request Filters are already added also relations added please import the file shared on whatsapp for permissions so you can see all relations

**Comment by sharjeelz** [comment]
@sunnan1  bro plz dont close untll we finish all requirements, i still need to check this

**Comment by sharjeelz** [comment]
@sunnan1  plz brother I already added persmissions send me the permissions that are new to add, tell names here I will add with your artisan command

**Comment by sharjeelz** [comment]
@sunnan1 
![image](https://user-images.githubusercontent.com/5259557/182948100-14c984af-14ca-42da-b92b-3c85f4c1241f.png)


this shows and no relations loads,

**Comment by sharjeelz** [comment]
@sunnan1  lets have a quick call tomorrow on this

**Comment by sunnan1** [comment]
> @sunnan1 also for images we need to find a way to show them plz research on this

On production it will auto pick the images from respective folders, the folder name for all modules is same as it in old admin

**Comment by sunnan1** [comment]
> @sunnan1 ![image](https://user-images.githubusercontent.com/5259557/182948100-14c984af-14ca-42da-b92b-3c85f4c1241f.png)
> 
> this shows and no relations loads,

![image](https://user-images.githubusercontent.com/16976650/183005394-4f506c3a-d443-4e74-a3bc-b51e43ee25cb.png)
All relations loaded, please remove the composer.lock file and remove vendor folder and then run composer install to re-install all packages again.

**Comment by sunnan1** [comment]
> @sunnan1 ![image](https://user-images.githubusercontent.com/5259557/182948100-14c984af-14ca-42da-b92b-3c85f4c1241f.png)
> 
> this shows and no relations loads,

![image](https://user-images.githubusercontent.com/16976650/183005394-4f506c3a-d443-4e74-a3bc-b51e43ee25cb.png)
All relations loaded, please remove the composer.lock file and remove vendor folder and then run composer install to re-install all packages again.

Status Changing now properly FCM notification will be send when URL is set on .env as it was on OLD admin

**Comment by sharjeelz** [comment]
I did what you said, above issue still came

**Comment by sharjeelz** [comment]
![image](https://user-images.githubusercontent.com/5259557/183155613-4737277b-edae-476d-8224-e44cd6f119db.png)
When creating transport as relation from inside service provider

**Comment by sunnan1** [comment]
You can't create a record in service provider relations as some of them are coming from pivot table, and they might have been updated from APIs.

**Comment by sunnan1** [comment]
Its Fixed, there was pivot table relation fixed.
