### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#4]
1. Able to upload images but when retrieved it says image not found.
2. Parent categories should be only visible on main and when clicked the child categories should be listed as in old admin
![image](https://user-images.githubusercontent.com/5259557/181822994-4e245b36-5775-4097-957e-3d77a5b18d76.png)

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182010937-6407ebe5-435f-4773-b361-dbfad04c900e.png)

The image shows properly, you just need to update the APP_URL in .env to 127.0.0.1:8000 for local

**Comment by sharjeelz** [comment]
@sunnan1  
1. Validation, and for this point "Parent categories should be only visible on main and when clicked the child categories should be listed as in old admin" (not fixed)
![image](https://user-images.githubusercontent.com/5259557/182240806-7bcd270c-c77e-47e4-be03-c5b7a8e42056.png)

**Comment by sunnan1** [comment]
Validation Added, Parent categories should be only visible on main and when clicked the child categories should be listed as in old admin" (not fixed) ( Not possible, NOVA has limitation )

**Comment by sharjeelz** [comment]
@sunnan1  what limitation plz explain

**Comment by sunnan1** [comment]
Added that relation now it showing like this

![image](https://user-images.githubusercontent.com/16976650/182777120-5acc1bab-5886-4527-8a5a-720128f79c57.png)

![image](https://user-images.githubusercontent.com/16976650/182777161-dc59e0ad-7aca-4f86-954a-1e9611c4bcd2.png)

**Comment by sunnan1** [comment]
Its Done

**Comment by sharjeelz** [comment]
Bro, in seeder all categories are going as parent, no children relation is getting defined

**Comment by sharjeelz** [comment]
Also I create a child category and assigned a parent, in DB it shows but on front end no children show

![image](https://user-images.githubusercontent.com/5259557/183263629-91e632d9-2db2-4108-a1be-2a267ddffc50.png)

**Comment by sharjeelz** [comment]
![image](https://user-images.githubusercontent.com/5259557/183263802-24ff5891-9764-475f-968a-6b17a28eab74.png)


but when I open this main category I dont see the child "OK"

**Comment by sharjeelz** [comment]
@sunnan1 the path for category images is not correct

**Comment by sharjeelz** [comment]
![image](https://user-images.githubusercontent.com/5259557/183264618-5d2ebb17-4cbe-4922-8951-08626a6d9683.png)


in seeder also plz append upload/catgories and in other models as well. so that old data can be retrieved aslo

**Comment by sharjeelz** [comment]
@sunnan1  this will be another overhead in API's already paths are defined, so we need only images names, not the paths plz,

**Comment by sharjeelz** [comment]
@sunnan1  suggestion

please change this on all places, create disks for every model that has image

![image](https://user-images.githubusercontent.com/5259557/183265160-2aeb1923-94dd-413e-82ec-8d4f9f72ca0c.png)


and store the image only not path in DB also

**Comment by sharjeelz** [comment]
@sunnan1  also when I am updating a parent category  we shoud not be able to see the parent category drop down

![image](https://user-images.githubusercontent.com/5259557/183265287-0f9fe86d-e1c2-4a8b-bca8-d28f6a962e60.png)

**Comment by sunnan1** [comment]
@sharjeelz brother fixed, Parent category dropdown removed and the category will be under category if you are in a category

![image](https://user-images.githubusercontent.com/16976650/183450340-ec2327b0-06a1-4759-b9a0-9fe6cb0f13e8.png)


![image](https://user-images.githubusercontent.com/16976650/183450392-60352073-e330-452d-a4f4-dc79da8f2a78.png)

**Comment by sunnan1** [comment]
The URL part is also fixed

**Comment by sharjeelz** [comment]
seeder is ont correct + only we need to show main categories on the first page as old admin now showing all 90, i think this can be fixed if we properly create seeder and add parent ids in table

**Comment by sharjeelz** [comment]
@sunnan1  created this issue on original repo now
