### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#5]
1. Phone validation is still not working
2. image issue also here I think its common
![image](https://user-images.githubusercontent.com/5259557/181823394-d0cf7b28-859c-49ff-b411-7ea937b012f9.png)

**Comment by sunnan1** [comment]
Validations : 
![image](https://user-images.githubusercontent.com/16976650/182011043-989d85d0-6399-4ab9-ab35-a26fd03fbfe1.png)

Fixed
