### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#6]
1. missing "allowed to post" field
2. Phone validation missing
3. balance should be numeric only ( this is new validation but we need to be good at work to fix things which are minute)
4. "language" **is** "mother language"
5. relations and fields are missing from detail page of users

**Comment by sunnan1** [comment]
missing "allowed to post" field ( Done )
    Phone validation missing ( Added )
    balance should be numeric only ( this is new validation but we need to be good at work to fix things which are minute) ( Added )
    "language" is "mother language" ( Done )
    relations and fields are missing from detail page of users ( Bank Accounts Relation Already Available )

**Comment by sharjeelz** [comment]
@sunnan1 

![image](https://user-images.githubusercontent.com/5259557/182243858-0a563dee-104a-415b-ba19-e21e05bb191e.png)

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182298504-cb7a8557-78f2-4982-8511-2644bb112186.png)

Added
