### ISSUE TITLE
Support Reasons

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#7]
1. Validation required for edit

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182011661-9df9f802-9266-4a44-8623-dab727bf22d6.png)

Added

**Comment by sharjeelz** [comment]
@sunnan1  the message is wrong it says already taken, 

![image](https://user-images.githubusercontent.com/5259557/182244258-9e8cfc3b-c2a8-4bbb-84b4-8d1815b3a244.png)

**Comment by sunnan1** [comment]
![image](https://user-images.githubusercontent.com/16976650/182299342-91414d5a-9a16-4c56-801b-729ec22e53aa.png)
Its working fine
