### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by sharjeelz** [sunnan1/mueenyNova#9]
1. Need validation
2. Need seeder (DB will be shared soon with all pre launch data that is required, plz see other tables as well)

**Comment by sunnan1** [comment]
Validation Added :

![image](https://user-images.githubusercontent.com/16976650/182011991-0bcf1b43-5a27-4613-abcc-87d4fbc8cccf.png)

For Seeder,

A Function is added that will update the location_novas table from location table

**Comment by sharjeelz** [comment]
@sunnan1  in location we have parent id also , so the new table should have same structure, so we can see countries first, then citifies and then areas, I believe this is same as categories

Validation is working now

**Comment by sunnan1** [comment]
I have searched it but there is no possibility to load the data based on relation, if you have any suggestion on it please share but i found no result for nova.
